// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 7/18/2026, 3:53:45 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/amartekadmin/Documents/GitHub/invitation-date/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amartekadmin/Documents/GitHub/invitation-date/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amartekadmin/Documents/GitHub/invitation-date/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amartekadmin/Documents/GitHub/invitation-date/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amartekadmin/Documents/GitHub/invitation-date/plugins/**/*.{js,ts,mjs}","/Users/amartekadmin/Documents/GitHub/invitation-date/composables/**/*.{js,ts,mjs}","/Users/amartekadmin/Documents/GitHub/invitation-date/utils/**/*.{js,ts,mjs}","/Users/amartekadmin/Documents/GitHub/invitation-date/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/amartekadmin/Documents/GitHub/invitation-date/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/amartekadmin/Documents/GitHub/invitation-date/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/amartekadmin/Documents/GitHub/invitation-date/app.config.{js,ts,mjs}","/Users/amartekadmin/Documents/GitHub/invitation-date/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;